#ifndef WUWE_FWD_H
#define WUWE_FWD_H

#include <gmp/gmp.hpp>

#define WUWE_NAMESPACE_BEGIN GMP_GENERATE_NAMESPACES_BEGIN(wuwe)
#define WUWE_NAMESPACE_END GMP_GENERATE_NAMESPACES_END(wuwe)

#define WUWE_AGENT_NAMESPACE_BEGIN GMP_GENERATE_NAMESPACES_BEGIN(wuwe, agent)
#define WUWE_AGENT_NAMESPACE_END GMP_GENERATE_NAMESPACES_END(wuwe, agent)

#endif // WUWE_FWD_H