name: Windows CI

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - memory
      - "release/**"
    tags:
      - "v*"

jobs:
  build-and-test:
    uses: ./.github/workflows/http-backends.yml
    with:
      platform: windows
